@hostname = http://localhost:8080

### Step 1 - Create a user
POST {{hostname}}/api/users
Content-Type: application/json

{
  "email": "tervis@test.com",
  "password": "123456"
}

### Step 2 - Login (grab token and refresh_token from the response)
POST {{hostname}}/api/login
Content-Type: application/json

{
  "email": "tervis@test.com",
  "password": "123456"
}

### Step 2.5 - Change the user's email and password (paste the "token" JWT from login response here)
PUT {{hostname}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYTY2OWFmNjEtMjM3Ni00MDJlLWI0ZDktY2E2ZTg0M2E2ZjllIiwiZXhwIjoxNzczNTE1NTU5LCJpYXQiOjE3NzM1MTE5NTl9.6HpN_mEKPn1gJNqTO26TWzn0QaS9JG3os99uRVBuYzM
Content-Type: application/json

{
  "email": "another@test.com",
  "password": "newpassword"
}

### Step 3 - Post a chirp (paste the "token" JWT from login response here)
POST {{hostname}}/api/chirps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYjhjZDAxNGUtZjhmOS00M2VjLTkxODctMmFmZWM2YzNlZDg3IiwiZXhwIjoxNzczNTE0NzgzLCJpYXQiOjE3NzM1MTExODN9.klgt0polbQ3Zp8RzyUADiRyK3fKG2pu-VucR4NJnt_g
Content-Type: application/json

{
  "body": "Vibe coding and trying to learn"
}

### Step 4 - Get a new access token (paste the "refresh_token" here)
POST {{hostname}}/api/refresh
Authorization: Bearer d033d161faddb8b9f12ffe4193705510c33c342a5965978958e85a9e816965e6

### Step 5 - Revoke the refresh token
POST {{hostname}}/api/revoke
Authorization: Bearer d033d161faddb8b9f12ffe4193705510c33c342a5965978958e85a9e816965e6

### 
GET {{hostname}}/api/chirps