@hostname = http://localhost:8080

### Get a single chirp by ID
get {{hostname}}/api/chirps/7f042df3-8f5a-48fb-9e8c-0b71ba8e3474

### Get all chirps
get {{hostname}}/api/chirps

### Post with authorzation header
post {{hostname}}/api/chirps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYzQxNjg1Y2YtZjllNi00ODUwLWJhNDItMWU2OGQ2OTQ2YzVkIiwiZXhwIjoxNzczNDQyODkwLCJpYXQiOjE3NzM0MzkyOTB9.7NpmPUpAxAcMBZCmbMvv2osXAwLZh4TDSk0gLTP-rKQ
Content-Type: application/json
{
  "body": "Hello, Chirpy! keRfuffle sharbert fornax"
}

### Login with valid credentials
post {{hostname}}/api/login
Content-Type: application/json  

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

### Test add user
post {{hostname}}/api/users
Content-Type: application/json

{
  "email": "travis.dunbar@gmail.com",
  "password": "password123"
}

### Validate a chirp
post {{hostname}}/api/chirps
Content-Type: application/json

{
  "body": "Hello, Chirpy! keRfuffle sharbert fornax",
  "user_id": "443a75c2-95f2-4672-83bc-cfd1f27449a9"
}

### Validate a chirp that is too long
post {{hostname}}/api/chirps
Content-Type: application/json

{
  "body": "Hello, world! This is a longer chirp that should be valid as well. We need to have more than 140 characters of text to make this fail. I think this is more than 140 characters.",
  "user_id": "b116dc2e-5b28-4096-bbfc-a2b9d82e04d6"
}

### Ping the frontend
get {{hostname}}/app

### Ping the healthz endpoint
get {{hostname}}/api/healthz

### Ping the healthz endpoint with POST (should NOT work)
post {{hostname}}/api/healthz

### Get metrics
get {{hostname}}/admin/metrics

### Reset hits (should be forbidden in non-dev environment)
post {{hostname}}/admin/reset

